### ISSUE TITLE
Wagtail 4.x support

### ISSUE THREAD

**Issue by Timusan** [dinoperovic/django-salesman#20]
Are there any plans to support Wagtail 4.x?

**Comment by dinoperovic** [comment]
@Timusan yes absolutely. I just have to find some time to do the update.

**Comment by dinoperovic** [comment]
Wagtail 4.0 and 4.1 support was added and released in version 1.1.5.

I would suggest using Wagtail 4.1 since the editor UI for custom models (orders in this case) was updated to be wider.
