### ISSUE TITLE
How long will django-salesman be maintained? More Maintainers needed?

### ISSUE THREAD

**Issue by Whizfactor** [dinoperovic/django-salesman#21]
Please i did love to know how long the project will be supported and maintained. I would love to know if i should go ahead and use it in production. How long will it receive updates?

**Comment by dinoperovic** [comment]
Hi, I plan on supporting the project indefinitely, if there is an issue feel free to submit it!

**Comment by Whizfactor** [comment]
Hi, would you be needing am extra maintainer? If so i did be happy to help
expand the project. What say you?

[Öñ [[[Šåţ one], [Ĵåñ one] 21, 2023], [07:45]] Dino Perovic <
***@***.***> ŵŕöţé: one two]

**Comment by dinoperovic** [comment]
Thanks, @Whizfactor. At the moment this project is quite small and is maintainable myself since I don't have many requests for adding features. If it gets to a point where it's too much, I would appreciate the help!
