### ISSUE TITLE
Django 4.2 support

### ISSUE THREAD

**Issue by madisvain** [dinoperovic/django-salesman#34]
**Describe the bug**
ERROR: Cannot install -r requirements.in (line 24), django-salesman==1.1.6 and django>=4.2 because these package versions have conflicting dependencies.

Django 4.2 was released and salesman I think would run just fine on the newer version as well but because of the Django version limitations it's not installable from pip.

Could we expand the Django versions it supports?

**Comment by dinoperovic** [comment]
@madisvain I will update once Wagtail v5 is released (currently in [RC](https://github.com/wagtail/wagtail/releases/tag/v5.0rc1)) as it adds Django 4.2 support as well.

**Comment by lucargir** [comment]
Hi @dinoperovic Wagtail v5 was released two days ago, just giving a ping to see if we can have this soon. I am trying to use Salesman with a new project with Wagtail v5, so let me know if I can be of any help :)

**Comment by dinoperovic** [comment]
Released Salesman [1.2.0](https://github.com/dinoperovic/django-salesman/releases/tag/1.2.0) which adds support for `Django-4.2` and `Wagtail-5.0`
