### ISSUE TITLE
iSort dependency prevents Poetry resolution in example project 

### ISSUE THREAD

**Issue by raybesiga** [dinoperovic/django-salesman#8]
**Describe the bug**

iSort dependency prevents poetry resolution 

**To Reproduce**

```bash
➜  django-salesman (master) ✔ poetry install -E example
The currently activated Python version 2.7.16 is not supported by the project (^3.6).
Trying to find and use a compatible version. 
Using python3 (3.8.5)
Creating virtualenv django-salesman-J2JSvch3-py3.8 in /Users/raymaun/Library/Caches/pypoetry/virtualenvs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PosixPath' is not defined
Updating dependencies
Resolving dependencies... (468.6s)

Writing lock file

[SolverProblemError]
The current project's Python requirement (2.7.16) is not compatible with some of the required packages Python requirement:
  - isort requires Python >=3.6,<4.0

Because isort (5.5.1) requires Python >=3.6,<4.0
 and no versions of isort match >=5.4,<5.5.1 || >5.5.1,<6.0, isort is forbidden.
So, because django-salesman depends on isort (^5.4), version solving failed.
➜  django-salesman (master) ✔ 
```

**Expected behavior**
That `poetry install -E example` would resolve the dependencies.

**Technical details:**
 - Python version: [e.g. 3.8.5]

**Comment by dinoperovic** [comment]
Hi @raybesiga, thanks for the report.

It looks to me like you're using Python `2.7.16` for your project.

> [SolverProblemError]
> The current project's Python requirement (2.7.16) is not compatible...
 
I've tested the process again using Python `3.8.5` and without issues.

Perhaps you can try and update poetry and ensure that the compatible version of python is used before installing.

```bash
python --version
poetry self update
poetry cache clear pypi --all
```

**Comment by raybesiga** [comment]
Hi @dinoperovic I have tried that. It appears that the issue may be related to [this issue](https://github.com/python-poetry/poetry/issues/655) in Poetry. I am running Python 3.8.5 but it picks up the system Python 2.7.  Guess I have a bit of work on my hands.

**Comment by dinoperovic** [comment]
@raybesiga Yes that's probably it. 
Great! Let me know if you need some assistance.
